- date: 2025-01-16
  name: "PLDI'25"
  type: Artifact Evaluation Committee
  link: https://pldi25.sigplan.org/committee/pldi-2025-pldi-research-artifacts-artifact-evaluation-committee

- date: 2024-01-16
  name: "PLDI'24"
  type: Artifact Evaluation Committee
  link: https://pldi24.sigplan.org/committee/pldi-2024-pldi-research-artifacts-artifact-evaluation-committee
